### ISSUE TITLE
502 Bad Gateway when showing or download configs

### ISSUE THREAD

**Issue by dpflick** [hoelsner/network-config-generator#8]
I tried recreating the template and re-running the builds but I keep getting this message.  I am running the recommended version of Ubuntu. 
502 Bad Gateway
nginx/1.10.3 (Ubuntu)
Any ideas where to start looking?
I tried a reboot of the server and an apt-get upgrade to see if it was the web server application failing.  It is only with 1 template (all others work).  I tried renaming the template and no go.  It worked fine yesterday so I am not sure what could be going on.

**Comment by dpflick** [comment]
Can I send you a private message with the input file?  What is interesting is that the input file has 4 lines (4 devices) and 2 work but 2 do not.  The 2 that work are very similar and the 2 that fail are a bit different (different variables set).

**Comment by dpflick** [comment]
ok, narrowed it down to the WAN_INTF variable.  If that variable is null, I get "Bad Gateway".  If I put in junk, it works.  I was thinking that the line 
% if WAN_INTF[0]=='g': 
may be causing it because in the CSV lines that work but are missing the RADIO_INTF as defined, the test is this: 
% if RADIO_INTF!='':
I am testing for the "g" for "gigabit interface" as opposed to "s" for serial interface so I can easily change the wan connection type in the input file and have it build the proper type interface.

**Comment by hoelsner** [comment]
Hello dpflick,

I think the issue is due to an unhandled error within the config template. I assume that you get the 502 because the Flask container crashes during the rendering of the configuration template. 

Can you please post the full configuration template (or at least the section that you've mentioned in your previous message) together with the parameters? You can also send this information via eMail to me if you can't share it in this thread.

Kind regards,
Henry
